<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="datagen"
    nsURI="http://www.csi.it/mddtools/datagen" nsPrefix="datagen">
  <eClassifiers xsi:type="ecore:EClass" name="DBAccessModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="schema" lowerBound="1"
        eType="ecore:EClass rdbmdl.ecore#//Schema"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="daopkgs" upperBound="-1"
        eType="#//DaoPackage" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codProdotto" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codComponente" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataAccessObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mainTable" eType="ecore:EClass rdbmdl.ecore#//Table"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pkGenerator" eType="#//PKGenerator"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inserter" eType="#//Inserter"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="finders" eType="#//Finders"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="updaters" eType="#//Updaters"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deleters" eType="#//Deleters"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaoPackage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dao" upperBound="-1" eType="#//DataAccessObject"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PKGenerator" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="SequencePKGenerator" eSuperTypes="#//PKGenerator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sequenceName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DBCommand" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Inserter" eSuperTypes="#//DBCommand"/>
  <eClassifiers xsi:type="ecore:EClass" name="Finders">
    <eStructuralFeatures xsi:type="ecore:EReference" name="finders" upperBound="-1"
        eType="#//Finder" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Finder" abstract="true" eSuperTypes="#//DBCommand"/>
  <eClassifiers xsi:type="ecore:EClass" name="FindByPK" eSuperTypes="#//Finder"/>
  <eClassifiers xsi:type="ecore:EClass" name="FindAll" eSuperTypes="#//Finder"/>
  <eClassifiers xsi:type="ecore:EClass" name="QBEFinder" eSuperTypes="#//Finder"/>
  <eClassifiers xsi:type="ecore:EClass" name="CustomFinder" eSuperTypes="#//Finder"/>
  <eClassifiers xsi:type="ecore:EClass" name="Updaters">
    <eStructuralFeatures xsi:type="ecore:EReference" name="updaters" upperBound="-1"
        eType="#//Updater" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Updater" abstract="true" eSuperTypes="#//DBCommand"/>
  <eClassifiers xsi:type="ecore:EClass" name="UpdateRow" eSuperTypes="#//Updater"/>
  <eClassifiers xsi:type="ecore:EClass" name="Deleters">
    <eStructuralFeatures xsi:type="ecore:EReference" name="deleters" upperBound="-1"
        eType="#//Deleter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Deleter" abstract="true" eSuperTypes="#//DBCommand"/>
  <eClassifiers xsi:type="ecore:EClass" name="DeleteByPK" eSuperTypes="#//Deleter"/>
</ecore:EPackage>
